[target.wasm32-unknown-emscripten]
rustflags = [
    # "-C",
    # "link-arg=-sALLOW_MEMORY_GROWTH",
    "-C",
    "link-arg=-sASYNCIFY",
    "-C",
    "link-arg=-sINITIAL_MEMORY=262144000",
      "-C",
    "link-arg=-MAXIMUM_MEMORY=262144000",
]
runner = "node"

[env]
#EMCC_STRICT="1"
# RUST_BACKTRACE="1"